//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amanet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AmanetEntities : DbContext
    {
        public AmanetEntities()
            : base("name=AmanetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calitati> Calitatis { get; set; }
        public virtual DbSet<Clienti> Clientis { get; set; }
        public virtual DbSet<ContracteProduse> ContracteProduses { get; set; }
        public virtual DbSet<Produse> Produses { get; set; }
        public virtual DbSet<ContracteAntet> ContracteAntets { get; set; }
        public virtual DbSet<lstPrintareContract> lstPrintareContracts { get; set; }
    
        public virtual int PROC_RptPrintareContract(Nullable<int> idContract)
        {
            var idContractParameter = idContract.HasValue ?
                new ObjectParameter("idContract", idContract) :
                new ObjectParameter("idContract", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_RptPrintareContract", idContractParameter);
        }
    }
}
