//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amanet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContracteAntet
    {
        public ContracteAntet()
        {
            this.ContracteProduses = new HashSet<ContracteProduse>();
        }
    
        public int id { get; set; }
        public int nrContract { get; set; }
        public System.DateTime dataContract { get; set; }
        public int idClient { get; set; }
        public Nullable<decimal> valoareCredit { get; set; }
        public Nullable<decimal> comisionProcZi { get; set; }
        public Nullable<decimal> valoareCreditZi { get; set; }
        public Nullable<decimal> valoareDebit { get; set; }
        public Nullable<int> nrZile { get; set; }
        public Nullable<System.DateTime> dataScadenta { get; set; }
        public string stareContract { get; set; }
        public string observatii { get; set; }
        public System.DateTime creatLa { get; set; }
        public System.DateTime modificatLa { get; set; }
        public bool inactiv { get; set; }
        public int lockVersion { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual ICollection<ContracteProduse> ContracteProduses { get; set; }
    }
}
