//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amanet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContracteProduse
    {
        public int id { get; set; }
        public int idContract { get; set; }
        public int idProdus { get; set; }
        public int idCalitate { get; set; }
        public int bucati { get; set; }
        public string descriere { get; set; }
        public Nullable<decimal> gramajPiesa { get; set; }
        public Nullable<decimal> gramajAur { get; set; }
        public System.DateTime creatLa { get; set; }
        public System.DateTime modificatLa { get; set; }
        public bool inactiv { get; set; }
        public int lockVersion { get; set; }
    
        public virtual Calitati Calitati { get; set; }
        public virtual Produse Produse { get; set; }
        public virtual ContracteAntet ContracteAntet { get; set; }
    }
}
