//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amanet
{
    using System;
    using System.Collections.Generic;
    
    public partial class lstPrintareContract
    {
        public int NumarContract { get; set; }
        public System.DateTime DataContract { get; set; }
        public string NumePrenume { get; set; }
        public string Domiciliul { get; set; }
        public string SerieCI { get; set; }
        public string NumarCI { get; set; }
        public string EliberatDe { get; set; }
        public Nullable<System.DateTime> EliberatLa { get; set; }
        public string Telefon { get; set; }
        public string Denumire { get; set; }
        public int Bucati { get; set; }
        public string Descriere { get; set; }
        public Nullable<decimal> GramajPiesa { get; set; }
        public Nullable<decimal> GramajAur { get; set; }
        public string Calitate { get; set; }
        public Nullable<decimal> ValoareCredit { get; set; }
        public Nullable<decimal> ComisionProcZi { get; set; }
        public Nullable<decimal> ValoareComisionZi { get; set; }
        public Nullable<decimal> ValoareDebit { get; set; }
        public Nullable<int> NrZileImprumut { get; set; }
        public Nullable<System.DateTime> DataScadenta { get; set; }
    }
}
